language: cpp

os:
  - freebsd # clang/libc++

before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = freebsd ]; then
      sudo pkg install -y meson pkgconf gtkmm30 nlohmann-json
    fi

script:
  - meson _build
  - meson compile -C _build
